version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "02:15"
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/docs"
  schedule:
    interval: monthly
    time: "02:20"
  open-pull-requests-limit: 10

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    time: "02:25"
  open-pull-requests-limit: 10
