SHELL:=/usr/bin/env bash

PROJECT = dailylog
PROJECT_PATH ?= $(shell git rev-parse --show-toplevel)
PROJECT_VERSION ?= $(shell grep ^current_version .bumpversion.cfg | awk '{print $$NF'} | tr '-' '.')
WHEELS=/home/jim/kbfs/private/jim5779/wheels

.PHONY: black mypy lint unit package test publish publish-test vars build chlog
vars:
	@echo "PROJECT: $(PROJECT)"
	@echo "PROJECT_VERSION: $(PROJECT_VERSION)"
	@echo "PROJECT_PATH: $(PROJECT_PATH)"

black:
	poetry run isort $(PROJECT) tests
	poetry run black $(PROJECT) tests

mypy: black
	poetry run mypy $(PROJECT) tests/*.py

lint: mypy
	poetry run flake8 $(PROJECT) tests
	poetry run doc8 -q docs

unit:
	poetry run pytest -s tests

package:
	poetry check
	poetry run pip check
	poetry run safety check --full-report

test: lint package unit

build: test
	poetry build
	cp dist/$(PROJECT)-$(PROJECT_VERSION)-py3-none-any.whl $(WHEELS)
	sync-wheels

# publish: build
# 	poetry publish

# publish-test: test build
# 	poetry publish -r test-pypi

chlog:
	github_changelog_generator -u wtfo-guru -p $(PROJECT)
	sed -i -e '/^$$/N;/^\n$$/D' ./CHANGELOG.md
	m2r2 --overwrite --anonymous-references CHANGELOG.md
	sed -i '/This Changelog was automatically generated by/d' ./CHANGELOG.rst
	mv -f ./CHANGELOG.rst ./docs/pages/changelog.rst
	poetry run doc8 -q docs

.DEFAULT:
	@cd docs && $(MAKE) $@
